import { bigint, bigserial, boolean, integer, pgTable, text, timestamp, uuid, uniqueIndex } from 'drizzle-orm/pg-core'

export const reservations = pgTable('reservations', {
  id: uuid('id').defaultRandom().primaryKey(),
  externalReservationId: text('external_reservation_id').notNull().unique(),
  ghlContactId: text('ghl_contact_id'), ghlOpportunityId: text('ghl_opportunity_id'), websiteCustomerId: text('website_customer_id'),
  travelerEmail: text('traveler_email').notNull(), tripId: text('trip_id').notNull(), tripName: text('trip_name').notNull(), destination: text('destination').notNull(),
  tripPriceMinor: bigint('trip_price_minor', { mode: 'number' }).notNull(), depositAmountMinor: bigint('deposit_amount_minor', { mode: 'number' }).notNull(), amountPaidMinor: bigint('amount_paid_minor', { mode: 'number' }).notNull().default(0), balanceDueMinor: bigint('balance_due_minor', { mode: 'number' }).notNull().default(0),
  reservationStatus: text('reservation_status').notNull().default('pending'), paymentStatus: text('payment_status').notNull().default('pending'), paymentPlanStatus: text('payment_plan_status').notNull().default('not_started'),
  stripeCustomerId: text('stripe_customer_id'), stripeCheckoutSessionId: text('stripe_checkout_session_id'), stripePaymentIntentId: text('stripe_payment_intent_id'), stripeSubscriptionId: text('stripe_subscription_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ emailTrip: uniqueIndex('reservations_email_trip_idx').on(t.travelerEmail, t.tripId) }))

export const stripeWebhookEvents = pgTable('stripe_webhook_events', { id: bigserial('id', { mode: 'number' }).primaryKey(), stripeEventId: text('stripe_event_id').notNull().unique(), eventType: text('event_type').notNull(), processed: boolean('processed').notNull().default(false), processingStatus: text('processing_status').notNull().default('received'), receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(), processedAt: timestamp('processed_at', { withTimezone: true }), externalReservationId: text('external_reservation_id'), errorCode: text('error_code'), errorMessage: text('error_message') })
export const payments = pgTable('payments', { id: uuid('id').defaultRandom().primaryKey(), externalReservationId: text('external_reservation_id').notNull(), stripeEventId: text('stripe_event_id').notNull(), stripeCheckoutSessionId: text('stripe_checkout_session_id'), stripePaymentIntentId: text('stripe_payment_intent_id'), stripeChargeId: text('stripe_charge_id'), paymentType: text('payment_type').notNull(), amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(), currency: text('currency').notNull(), status: text('status').notNull(), refundedAmountMinor: bigint('refunded_amount_minor', { mode: 'number' }).notNull().default(0), paidAt: timestamp('paid_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const crmSyncState = pgTable('crm_sync_state', { externalReservationId: text('external_reservation_id').primaryKey(), ghlContactId: text('ghl_contact_id'), ghlOpportunityId: text('ghl_opportunity_id'), lastSuccessfulSync: timestamp('last_successful_sync', { withTimezone: true }), lastSyncStatus: text('last_sync_status'), retryCount: integer('retry_count').notNull().default(0), lastError: text('last_error'), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
